SET SCHEMA "NEO_1D7T58VJIG1IUJMCH9P1XLHN7";

DROP TYPE PAL_AP_T_DATA;
CREATE TYPE PAL_AP_T_DATA AS TABLE ("ORDERID" INT, "PRODUCTID" INT);

DROP TYPE PAL_AP_T_PARAMS;
CREATE TYPE PAL_AP_T_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));

DROP TYPE PAL_AP_T_RULES;
CREATE TYPE PAL_AP_T_RULES AS TABLE ("PRERULE" VARCHAR(500), "POSTRULE" VARCHAR(500), "SUPPORT" DOUBLE, "CONFIDENCE" DOUBLE, "LIFT" DOUBLE);

DROP TYPE PAL_AP_T_PMML;
CREATE TYPE PAL_AP_T_PMML AS TABLE ("ID" INT, "PMMLMODEL" VARCHAR(5000));

DROP TABLE PAL_AP_SIGNATURE;
CREATE COLUMN TABLE PAL_AP_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_AP_SIGNATURE VALUES (1, 'NEO_1D7T58VJIG1IUJMCH9P1XLHN7.PAL_AP_T_DATA', 'in');
INSERT INTO PAL_AP_SIGNATURE VALUES (2, 'NEO_1D7T58VJIG1IUJMCH9P1XLHN7.PAL_AP_T_PARAMS', 'in');
INSERT INTO PAL_AP_SIGNATURE VALUES (3, 'NEO_1D7T58VJIG1IUJMCH9P1XLHN7.PAL_AP_T_RULES', 'out');
INSERT INTO PAL_AP_SIGNATURE VALUES (4, 'NEO_1D7T58VJIG1IUJMCH9P1XLHN7.PAL_AP_T_PMML', 'out');

CALL "HCP"."HCP_AFL_WRAPPER_ERASER"('PAL_AP');
 
CALL "HCP"."HCP_AFL_WRAPPER_GENERATOR"('PAL_AP','AFLPAL','APRIORIRULE',PAL_AP_SIGNATURE);  

INSERT INTO "_SYS_BIC"."p013346trial.hihanaxs.pal_ap.data::my_models.AP_PARAMS" VALUES ('MIN_SUPPORT', null, 0.001, null);
INSERT INTO "_SYS_BIC"."p013346trial.hihanaxs.pal_ap.data::my_models.AP_PARAMS" VALUES ('MIN_CONFIDENCE', null, 0.001, null);
INSERT INTO "_SYS_BIC"."p013346trial.hihanaxs.pal_ap.data::my_models.AP_PARAMS" VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO "_SYS_BIC"."p013346trial.hihanaxs.pal_ap.data::my_models.AP_PARAMS" VALUES ('MAX_ITEM_LENGTH', 10, null, null);
INSERT INTO "_SYS_BIC"."p013346trial.hihanaxs.pal_ap.data::my_models.AP_PARAMS" VALUES ('PMML_EXPORT', 0, null, null);
INSERT INTO "_SYS_BIC"."p013346trial.hihanaxs.pal_ap.data::my_models.AP_PARAMS" VALUES ('OPTIMIZATION_TYPE', 0, null, null);
INSERT INTO "_SYS_BIC"."p013346trial.hihanaxs.pal_ap.data::my_models.AP_PARAMS" VALUES ('IS_RECALCULATE', 0, null, null);


	